config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :profiles do
    resources :users
end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_one :profile

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index  
end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  respond_to :html

  def index
	end

  def show
    @profile = Profile.find(params[:id])
    respond_with(@profile)
  end

  def new
    @profile = Profile.new 
  end

  def create
    # profile = Profile.new(user: current_user)
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    @profile.save
    #@user = current_user
    #@user.profile.create (params[:user_id])
    #redirect_to user.profile
  end


private

  def profile_params
    params.require(:profile).permit(
      :name,
      :start_date, 
      :team_captain, 
      :address, 
      :working_status, 
      :vip_status, 
      :title, 
      :lyft, 
      :pam, 
      :endzone
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class = "container">
<div class="col-lg-6 col-lg-offset-3 text-center">

<h1>Welcome to CookBook!</h1>

            <% if user_signed_in? %>
            <li><%= link_to "Update Profile", new_profile_path(current_user) %></li>
            <li><%= link_to 'Change Password', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myzenplace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/"><%= image_tag 'logos/ks_logo.png', :class => "navbar-brand logo" %></a>
        </div>

  

          
            
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<body>

<%= yield %>

</body>
</html>

app/views/profiles/new.html.erb
<div>
<%= form_for @profile do |f| %>
	Name: <%= f.text_field :name %>
	<br>
	Start Date: <%= f.text_field :start_date %>
	<br>
	Team Captain: <%= f.text_field :team_captain %>
	<br>
	Address: <%= f.text_field :address %>
	<br>
	Working Status: <%= f.text_field :working_status %>
	<br>
	VIP Status: <%= f.text_field :vip_status %>
	<br>
	Title: <%= f.text_field :title %>
	<br>
	Lyft: <%= f.text_field :lyft %>
	<br>
	PAM: <%= f.text_field :pam %>
	<br>
	Endzone: <%= f.text_field :endzone %>
	<br>
	<%= f.submit "Complete Profile" %>
<% end %>

</div>

app/views/profiles/show.html.erb
<%= @profile.name %> <br>
<%= @profile.start_date %> <br>
<%= @profile.team_captain %> <br>
<%= @profile.address %> <br>
<%= @profile.working_status %> <br>
<%= @profile.vip_status %> <br>
<%= @profile.title %> <br>
<%= @profile.lyft %> <br>
<%= @profile.pam %> <br>
<%= @profile.endzone %> <br>